### PR TITLE
option aw-ignore-other-frames

### PR DESCRIPTION
**Pull request by dradetsky**
Add option to only build window list from current frame. Handy if you have multiple frames via emacs server. I can switch more effectively between the frames with my window manager.

### CODE REVIEW

**Comment by abo-abo** [comment]
Doesn't this work already:

    (setq aw-scope 'frame)

**Comment by dradetsky** [comment]
yes, i missed that somehow. this is not necessary. Might want better
documentation though.

**Comment by abo-abo** [comment]
> Might want better
> documentation though.

Patch welcome. Or just write it up on the wiki if you want.

**Comment by dradetsky** [comment]
sure

**Pull request closed without merging**
