### PR TITLE
Add execute-command-other-window

### PR DESCRIPTION
**Pull request by nickdrozd**

### CODE REVIEW

**Comment by abo-abo** [comment]
What's the use-case for this?

**Comment by nickdrozd** [comment]
Say I have four windows, I'm currently in window `a`, I have a compilation buffer in window `d`, and I want to recompile. Currently this will require two window switch operations (I use <kbd>C-o</kbd> for AW dispatch): <kbd>C-o d g C-o a</kbd>. With this function, I only need one: <kbd>C-o e d g</kbd>.

This accepts arbitrary key sequences, like opening a Projectile shell buffer: <kbd>C-o e f C-c p x s</kbd>. That will open the shell buffer in window `f` and then switch back.

I don't know if this is the best way to read key sequences, but I've been using the command for a while and it seems to work fine.

**Comment by abo-abo** [comment]
Thanks.

**Comment by duianto** [comment]
The `aw-dispatch-alist` name: `Execute Command Other Window` 
sounds like it might ask for a command name.

Since the prompt says: `Enter key sequence: `
maybe a more descriptive name would be: `Key Sequence Other Window`

Even if it isn't renamed, the two action lists in the readme 
https://github.com/abo-abo/ace-window#change-the-action-midway
https://github.com/abo-abo/ace-window#aw-dispatch-alist
is missing an entry for this command.

**Comment by nickdrozd** [comment]
That's a good point. I don't have strong opinions either way.

**Comment by duianto** [comment]
If either one or two additional actions were added that opens the `M-x` or/and `Eval:` prompts in the other window.

Then at least one of them could be called `Execute Command Other Window`.

**Pull request closed without merging**
