### PR TITLE
Add fair window splitting

### PR DESCRIPTION
**Pull request by wmedrano**
Splits either vertically or horizontally, whatever is best based on the selected window's dimensions.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. The key <kbd>f</kbd> conflicts with my personal setting `(setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))`. Can you choose a key that's not on the home row?

Additionally, since `ace-window` is on GNU ELPA, I need the contributors to have the Emacs Copyright Assignment for changes larger that 15 lines. Do you want to get it (it will work for all ELPA packages, org-mode and core Emacs as well)?

**Comment by wmedrano** [comment]
Oops, sorry about the home row, should've read the docs. Is <kbd>c</kbd> okay?

Also, just signed up for Emacs Copywright Assignment.

**Comment by abo-abo** [comment]
> Oops, sorry about the home row, should've read the docs. Is c okay?

Yes.

> Also, just signed up for Emacs Copywright Assignment.

Thanks, let me know when you have an answer from them.

**Comment by wmedrano** [comment]
Update: got approval from my company, now seeking GNU

**Comment by wmedrano** [comment]
Update: CA complete

**Comment by abo-abo** [comment]
Thanks! Please remind the copyright clerk to propagate the changes to `fencepost.gnu.org:/home/g/gnuorg/copyright.list`, your email isn't there yet.

**Comment by wmedrano** [comment]
Clerk said it gets updated based on a cron job.

Is it there yet?

**Comment by abo-abo** [comment]
Thanks, merged.

**Pull request closed without merging**
