### PR TITLE
Fix for horizontally scrolled windows and when scroll-margin is non-zero

### PR DESCRIPTION
**Pull request by rswgnu**
Commits #609dfa9,  #dac5938 and #c35a044 should fix issues #166 and #142.

They might fix issue #78 as well; I have not tested that.

The only remaining windows that will not always display the leading/overlay character in the buffer itself are those with asynchronous outputs such as *Messages* and shell buffers where the displayed portion of the buffer may change after ace-window tries to add the overlay.

### CODE REVIEW

**Comment by mrkkrp** [comment]
I confirm that this fixes #166.

**Comment by abo-abo** [comment]
@rswgnu Thanks. This repository has a linear Git history rule. Please try to adhere to it, because I had to spend 15 minutes just to merge the commit properly. Granted, it would be less time if I had figured out a simpler way to do it right away.

Here it is, for (my) future reference:

```sh
git checkout master
git reset --hard origin/master
git checkout pull/origin/168 -- *.el
cp ace-window.el ace-window-1.el
git reset --hard origin/master
git merge pull/origin/168
git format-patch origin/master
git reset --hard origin/master
git am 0002-*
mv ace-window-1.el ace-window.el
git add ace-window.el
git am --continue
rm *.patch
```

The method is sub-optimal, since all commits were basically squished into one. But it worked out in this case.

@mrkkrp Thanks for testing.

**Comment by rswgnu** [comment]
I am not sure what happened here as I checked out a fresh copy of your master branch and then started applying my recwn fixes to it and then pushed.  What else can I do?

**Comment by rswgnu** [comment]
@abo-abo, nice work reviewing, integrating and closing all those issues.

**Comment by abo-abo** [comment]
> I am not sure what happened here as I checked out a fresh copy of your master branch and then started applying my recwn fixes to it and then pushed. What else can I do?

I think you used `git-merge` at some point, since I saw a merge commit. Just use `git-rebase` instead, and everything should work fine. Thanks for the fixes.

**Comment by rswgnu** [comment]
Yes, I always use merges up to now.

-- Bob

**Pull request closed without merging**
