### PR TITLE
Rebased PR to sync our branches

### PR DESCRIPTION
**Pull request by rswgnu**
This is as clean as I could make it with rebase.  The changes are short enough to read manually I think.  Then apply and tweak any minor differences that remain.  Thanks.

I updated documentation and added aw-ignore-p improvements as well.  I still have to rebase the avy PR.

### CODE REVIEW

**Comment by abo-abo** [comment]
Looks like you have to rebase this PR as well - there's a merge confict.

**Comment by rswgnu** [comment]
I know.  It is small.  I was hoping you could handle that manually yourself.

**Comment by rswgnu** [comment]
I have made the conflicts as small as I can now.  You could easily resolve these by hand (there is only one that involves a logic change) and then change anything you want.

**Comment by abo-abo** [comment]
Thanks. I merged as much as I could. I used a simple copy-paste approach for rebasing: Git was getting too confused.

I'm not convinced that non-selectable buffers should be highlighted in ace-window-display-mode. If you want the other changes for ace-window-display-mode, open a new PR with some explanation.

There was a bit about checking `aw-action` to be a window: it's not a window, it's a function like it says in the doc.

**Comment by rswgnu** [comment]
On Mon, Dec 11, 2017 at 11:59 AM, Oleh Krehel <notifications@github.com>
wrote:

> Thanks. I merged as much as I could. I used a simple copy-paste approach
> for rebasing: Git was getting too confused.
>
> I'm not convinced that non-selectable buffers should be highlighted in
> ace-window-display-mode.
>

​For example, the Treemacs package uses a side window to display a
dired-like file manager that stays in the frame until it is quit.  It's
sets the 'no-other-window property because its window should not generally
be selected when switching windows.  But at some point, you want to jump to
its window and execute commands.  So ace-window could provide direct access
to it if it were labeled.  I would think the windows you would never want
to jump to at 1% or less.

> There was a bit about checking aw-action to be a window: it's not a
> window, it's a function like it says in the doc.
>
​There was a scenario where this happened and that led to the code.  I'll
have to look back at what triggered this; maybe it was the initial way
mouse clicks on windows were handled.
I agree it would be better if such logic were not needed.  Let me get back
to you on this one.

**Pull request closed without merging**
